/**
 * Define Global Variables
 * 
*/
const allSections = document.getElementsByTagName("section");
const navigation = document.getElementsByTagName("nav")[0];
const navList = document.getElementById("navbar__list");
const list = document.getElementsByTagName("li");



// build the nav
function buildingNav(){
    for(const section of allSections){
        //console.log(section);
        //grabbed the section created's data-nav word. 
        const sectionTitle = section.dataset.nav;
        // adding a list element/node
        const node = document.createElement("li"); 
        const linkNode = document.createElement("a");
        //created a variable with the section title as its value.
        const textnode = document.createTextNode(sectionTitle); // Create a text node
        //combined the section to the link as its child and gives text to the li. 
        linkNode.appendChild(textnode);
        //added the id and named it
        node.id = sectionTitle;
        //linkNode.href = "#"; 
        //combined the list node to the navigation bar.
        node.appendChild(linkNode)
        navList.appendChild(node);
    }
}
buildingNav(); 


//Scrolling smoothly and connecting the autogenerated Nav.list.Id to the section.id
document.getElementById("About").addEventListener("click", function() {
  console.log('the ABOUT button was clicked')
  document.getElementById('section1').scrollIntoView({behavior: "smooth"})
  });
document.getElementById("Aruba").addEventListener("click", function() {
  console.log('the ABOUT button was clicked')
  document.getElementById('section2').scrollIntoView({behavior: "smooth"})
  });
document.getElementById("Jamaica").addEventListener("click", function() {
  console.log('the ABOUT button was clicked')
  document.getElementById('section3').scrollIntoView({behavior: "smooth"})
  });
document.getElementById("Bermuda").addEventListener("click", function() {
  console.log('the ABOUT button was clicked')
  document.getElementById('section4').scrollIntoView({behavior: "smooth"})
  }); 
document.getElementById("Bahamas").addEventListener("click", function() {
  console.log('the ABOUT button was clicked')
  document.getElementById('section5').scrollIntoView({behavior: "smooth"})
  });   
document.getElementById("Key Largo").addEventListener("click", function() {
  console.log('the ABOUT button was clicked')
  document.getElementById('section6').scrollIntoView({behavior: "smooth"})
  });
document.getElementById("Montego").addEventListener("click", function() {
  console.log('the ABOUT button was clicked')
  document.getElementById('section7').scrollIntoView({behavior: "smooth"})
  });
document.getElementById("Florida Keys").addEventListener("click", function() {
  console.log('the ABOUT button was clicked')
  document.getElementById('section8').scrollIntoView({behavior: "smooth"})
  });



//EVENT LISTENERS
const pageClicked = document.querySelector('body');
pageClicked.addEventListener('click', function () {
    console.log('The landing page was clicked!');
    }
    );

//SCROLL TO TOP BUTTON. 
backToTopButton = document.getElementById("scrollTopButton");
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
    backToTopButton.style.display = "block";
  } else {
    backToTopButton.style.display = "none";
  }
}
function backToTop() {
  document.body.scrollTop = 0; // For Safari
  document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}


